// <auto-generated />
using DMCWale.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DMCWale.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505093000_AddAgentSupplierCodeToUserProfiles")]
    partial class AddAgentSupplierCodeToUserProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
