<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <ProjectReference Include="..\DMCWale.Data\DMCWale.Data.csproj" />
    <ProjectReference Include="..\DMCWale.Repo\DMCWale.Repo.csproj" />
  </ItemGroup>

</Project>
